apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-prediction-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: diabetes-prediction
  template:
    metadata:
      labels:
        app: diabetes-prediction
    spec:
      containers:
      - name: diabetes-prediction-container
        image: diabetes-prediction:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: diabetes-prediction-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: diabetes-prediction